import { createModuleFederationConfig } from '@module-federation/modern-js';

export default createModuleFederationConfig({
    name: 'remoteDesignSystem',
    manifest: {
        filePath: 'static',
    },
    filename: 'static/remoteEntry.js',
    exposes: {
        './DesignSystemRootStyles': './src/styles/design-system-styles.ts',
        './VisuallyHidden': './src/components/accessibility/VisuallyHidden.tsx',
        './CTAButton': './src/components/button/CTAButton.tsx',
        './LinkIconButton': './src/components/button/LinkIconButton.tsx',
        './PrimaryButton': './src/components/button/PrimaryButton.tsx',
        './SecondaryButton': './src/components/button/SecondaryButton.tsx',
        './SimpleButton': './src/components/button/SimpleButton.tsx',
        './Checkbox': './src/components/form/Checkbox.tsx',
        './Checkboxes': './src/components/form/Checkboxes.tsx',
        './DatePicker': './src/components/form/DatePicker.tsx',
        './DateProvider': './src/components/form/DateProvider.tsx',
        './Fieldset': './src/components/form/Fieldset.tsx',
        './HelperText': './src/components/form/HelperText.tsx',
        './TextInput': './src/components/form/TextInput.tsx',
        './PasswordInput': './src/components/form/PasswordInput.tsx',
        './EmailInput': './src/components/form/EmailInput.tsx',
        './MonetaryInput': './src/components/form/MonetaryInput.tsx',
        './Label': './src/components/form/Label.tsx',
        './MultiSelect': './src/components/form/MultiSelect.tsx',
        './RadioGroup': './src/components/form/RadioGroup.tsx',
        './Select': './src/components/form/Select.tsx',
        './SelectAllCheckbox': './src/components/form/SelectAllCheckbox.tsx',
        './Textarea': './src/components/form/Textarea.tsx',
        './Tab': './src/components/tabular/Tab.tsx',
        './TabList': './src/components/tabular/TabList.tsx',
        './TabPanel': './src/components/tabular/TabPanel.tsx',
        './Tabs': './src/components/tabular/Tabs.tsx',
        './TabsContext': './src/components/tabular/TabsContext.tsx',
        './Heading': './src/components/typography/Heading.tsx',
        './Paragraph': './src/components/typography/Paragraph.tsx',
        './UnorderedList': './src/components/typography/UnorderedList.tsx',
        './Accordion': './src/components/Accordion.tsx',
        './Alert': './src/components/Alert.tsx',
        './Badge': './src/components/Badge.tsx',
        './Chip': './src/components/Chip.tsx',
        './Dialog': './src/components/Dialog.tsx',
        './Divider': './src/components/Divider.tsx',
        './Icon': './src/components/Icon.tsx',
        './InlineLink': './src/components/InlineLink.tsx',
        './Header': './src/components/navigation/Header.tsx',
        './Footer': './src/components/navigation/Footer.tsx',
        './AccountLinks': './src/components/AccountLinks.tsx',
        './Form': './src/components/form/Form.tsx',
        './PhoneInput': './src/components/form/PhoneInput.tsx',
        './MuiTable': './src/components/table/MuiTable.tsx',
        './MuiTableBody': './src/components/table/MuiTableBody.tsx',
        './MuiTableCell': './src/components/table/MuiTableCell.tsx',
        './MuiTableHead': './src/components/table/MuiTableHead.tsx',
        './MuiTableRow': './src/components/table/MuiTableRow.tsx',
        './MuiCollapse': './src/components/table/MuiCollapse.tsx',
        './FeatureStatus': './src/components/FeatureStatus.tsx',
        // './DesignSystemSpacing': './src/styles/spacing.ts'
    },
    shared: {
        react: { singleton: true, requiredVersion: '18.3.1' },
        'react-dom': { singleton: true, requiredVersion: '18.3.1' },
        'react-router-dom': { singleton: true, requiredVersion: '18.3.1' },
        clsx: { singleton: true, requiredVersion: '2.1.1' },
        'react-hook-form': { singleton: true, requiredVersion: '7.54.2' },
    },
});
