[build]
  publish = "dist"
  command = "modern deploy"

[[headers]]
  for = "/static/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://payer-portal.netlify.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
